### ISSUE TITLE
Where are the crash reports stored?

### ISSUE THREAD

**Issue by rahulas** [karthyks/Crashlytics-Android#1]
I didn't understand that where will be these crash reports stored on device. Are they stored on device or will be sent to any mail. Can you please clear these things and if possible update your readMe file with these info.

**Comment by karthyks** [comment]
The crash will be stored locally in the database, only if the CustomCrashHandler throws any Exception. And the stored data will be synced based on CrashEvent.ALARM_FREQUENCY (default 15 minutes), and triggers the onEventOccurred method until it passes.

**Comment by karthyks** [comment]
I am closing this issue now. Hope your doubt is clarified.
